version: '3.8'

services: 
  express-app: 
    image: vaskivaara/exercise3_1:latest
    ports: 
      - 8000:8080  
    labels:
      - "com.centurylinklabs.watchtower.enable=true"  
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_POLL_INTERVAL=30 
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_DEBUG=true 
    container_name: watchtower
  
    