version: '3.8'

services: 
  frontend: 
    image: example-frontend:1.14.0
    networks:
      - hyrule
  redis:   
    image: redis
    networks:
      - hyrule
  db:
    image: postgres:16.3
    restart: unless-stopped
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: kewl
    networks: 
      - hyrule  
    volumes:
      - ./database:/var/lib/postgresql/data 
  backend:
    image: example-backend:1.14.1
    depends_on:
      - db
    environment: 
      - REDIS_HOST=redis
      - REQUEST_ORIGIN=http://frontend
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=kewl
    networks:
      - hyrule
  nginx:
    image: nginx:1.25.5
    networks:
      - hyrule
    ports:
      - 80:80  
    volumes:
      - ./nginx.config:/etc/nginx/nginx.conf

networks:
  hyrule:
