version: '3.8'

services: 
  frontend: 
    image: example-frontend:1.14.0
    ports: 
      - 5000:5000  
  backend:
    image: example-backend:1.14.1
    ports: 
      - 8080:8080
    environment: 
      - REQUEST_ORIGIN=http://localhost:5000
     
  
      


