name: Release Node.js app

on:
  push:
    branches:
      - main

jobs:
  buildAndPush:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: verify checkout
        run: ls
